name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'
    
env:
  DOCKERHUB_REPO: pnguyen4/myimage

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo to runner
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      

    - name: Push to DockerHub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ env.DOCKERHUB_REPO }}
        tag_with_ref: true
        