name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'
    
env:
  nguyepu/pnguyen4: myimage

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo to runner
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build -t myimage -f ./Dockerfile.txt
      
    - name: Run container from image
      run: docker run -d -p 8080:80 myimage
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: nguyepu
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Tag image
      run: docker tag myimage:latest nguyepu/pnguyen4-repo:latest
        
    - name: Push Docker Image
      run: docker push nguyepu/pnguyen-repo:latest  
