name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'
    
env:
  DOCKERHUB_REPO: pnguyen4-repo

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo to runner
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Generate image tags
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}
        tags: |
          latest
          ${{ github.ref }}
          ${{ github.sha }}
    - name: Build and push
      id: docker_build 
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        context: .
        file: ./Dockerfile
        