name: Build and Push Docker Image

on:
  push:
    branches: [main]
    workflow-dispatch:
    tags:
env:
  DOCKERHUB_REPO: pnguyen4-repo

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo to runner
      uses: actions/checkout@v2


    - name: Generate image tags
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}
        tags: |
          latest
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=sha
          
    - name: Build and push
      id: docker_build 
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        context: .
        file: ./Dockerfile
        
