name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'
    
env:
  DOCKERHUB_REPO: myimage

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo to runner
      uses: actions/checkout@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:latest